# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Feature.create(name: 'Acceso para discapacitados')
Feature.create(name: 'Aire acondicionado')
Feature.create(name: 'Alarma de seguridad')
Feature.create(name: 'Alberca')
Feature.create(name: 'Amueblado')
Feature.create(name: 'Área de juegos infantiles')
Feature.create(name: 'Áreas verdes')
Feature.create(name: 'Asador')
Feature.create(name: 'Balcón')
Feature.create(name: 'Bodega')
Feature.create(name: 'Canchas de squash')
Feature.create(name: 'Canchas de tenis')
Feature.create(name: 'Chimenea')
Feature.create(name: 'Cisterna')
Feature.create(name: 'Cocina integral')
Feature.create(name: 'Cuarto de servicio')
Feature.create(name: 'Elevador')
Feature.create(name: 'Estacionamiento para visitas')
Feature.create(name: 'Gas natural')
Feature.create(name: 'Gimnasio')
Feature.create(name: 'Jacuzzi')
Feature.create(name: 'Lavadora')
Feature.create(name: 'Línea telefónica')
Feature.create(name: 'No se admiten mascotas')
Feature.create(name: 'No se permite fumar')
Feature.create(name: 'Patio')
Feature.create(name: 'Portero')
Feature.create(name: 'Roof Garden')
Feature.create(name: 'Salón de usos múltiples')
Feature.create(name: 'Secadora')
Feature.create(name: 'Terraza')
Feature.create(name: 'Vigilancia')
